// קובץ build.gradle הראשי של הפרויקט
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // הגדרת גרסת ה-Plugin של אנדרואיד לבניית הפרויקט
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
